<?php
// Include the main configuration file to make constants available.
require_once 'config.php';

// --- Failsafe Redirect ---
// Get the page name from the URL.
$pageName = isset($_GET['page']) ? trim($_GET['page']) : null;

// If no page name is provided, this script was loaded directly without the
// proper context. Redirect to the default journal page to ensure the
// JavaScript application has a valid starting point.
if (empty($pageName)) {
    $default_page_name = date('Y-m-d');
    $redirect_url = 'page.php?page=' . urlencode($default_page_name);
    header('Location: ' . $redirect_url, true, 302);
    exit;
}

// --- Frontend Configuration ---
// Pass relevant backend configuration settings to the frontend JavaScript.
// This uses the PROPERTY_WEIGHTS constant from config.php.
$renderInternal = PROPERTY_WEIGHTS[3]['visible_in_view_mode'] ?? false;
$showInternalInEdit = PROPERTY_WEIGHTS[3]['visible_in_edit_mode'] ?? true;

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo htmlspecialchars($pageName); ?> - notd</title>
    <link rel="icon" type="image/svg+xml" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>📝</text></svg>">
    
    <!-- Fonts and Core Styles -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    
    <!-- Theme and App Styles -->
    <?php include 'assets/css/theme_loader.php'; ?>
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" href="assets/css/icons.css">
    <link rel="stylesheet" href="assets/css/calendar.css">
    
    <!-- Libraries -->
    <script src="assets/libs/feather.min.js"></script>
    <script src="assets/libs/marked.min.js"></script>
    <script src="assets/libs/Sortable.min.js"></script>
    
    <script>
        // Pass server-side configuration to JavaScript
        window.APP_CONFIG = {
            RENDER_INTERNAL_PROPERTIES: <?php echo json_encode($renderInternal); ?>,
            SHOW_INTERNAL_PROPERTIES_IN_EDIT_MODE: <?php echo json_encode($showInternalInEdit); ?>
        };
    </script>
</head>
<body>
    <div id="splash-screen">
        <div class="time-date-container">
            <div id="clock" class="clock">12:00</div>
            <div id="date" class="date">Monday, 1 January</div>
        </div>
        <div id="splash-background-bubbles-canvas">
            <!-- Canvas for dynamic bubbles -->
        </div>
        <div id="splash-orb-container">
            <div id="splash-orb-inner-core">
                <div id="splash-orb-text-container">
                    <p id="splash-orb-text">notd</p>
                </div>
                <div id="splash-orb-perimeter-dots">
                    <!-- Dots will be generated by JS -->
                </div>
            </div>
        </div>
    </div>
    
    <div class="app-container">
        <!-- Left Sidebar -->
        <div id="left-sidebar-outer">
            <button id="toggle-left-sidebar-btn" class="sidebar-toggle-btn left-toggle"><i data-feather="x"></i></button>
            <div id="left-sidebar" class="sidebar left-sidebar">
                <div class="sidebar-content">
                    <div class="app-header">
                        <a href="/" id="app-title" class="app-title">notd</a>
                    </div>
                    <div class="sidebar-section">
                        <div id="calendar-widget" class="calendar-widget">
                            <div class="calendar-header">
                                <button id="prev-month-btn" class="arrow-btn"><i data-feather="chevron-left"></i></button>
                                <span id="current-month-year" class="month-year-display"></span>
                                <button id="next-month-btn" class="arrow-btn"><i data-feather="chevron-right"></i></button>
                            </div>
                            <div class="calendar-grid calendar-weekdays">
                                <span>M</span><span>T</span><span>W</span><span>T</span><span>F</span><span>S</span><span>S</span>
                            </div>
                            <div id="calendar-days-grid" class="calendar-grid calendar-days"></div>
                        </div>
                    </div>
                    <div class="search-section">
                        <input type="text" id="global-search-input" placeholder="Search..." class="search-input">
                        <div id="search-results" class="search-results"></div>
                    </div>
                    <div class="recent-pages">
                        <h3>Recent Pages</h3>
                        <div id="page-list"></div>
                    </div>
                    <div class="sidebar-footer">
                        <button id="open-page-search-modal-btn" class="action-button full-width-button">
                            <i data-feather="search"></i> Search or Create Page
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <!-- Main Content -->
        <div id="main-content" class="main-content">
            <div class="page-title-container">
                <h1 id="page-title" class="page-title">
                    <!-- Page title and breadcrumbs populated by JS -->
                </h1>
                <div id="page-properties-container" class="page-properties-inline"></div>
            </div>
            <div id="page-content" class="page-content">
                <!-- Page content will be rendered here -->
            </div>
            <div id="note-focus-breadcrumbs-container"></div>
            <div id="notes-container" class="outliner">
                <!-- Notes will be rendered here by JavaScript -->
            </div>
            <div id="child-pages-container">
                <!-- Child pages will be rendered here by JavaScript -->
            </div>
            <button id="add-root-note-btn" class="action-button round-button" title="Add new note to page">
                <i data-feather="plus"></i>
            </button>
        </div>

        <!-- Right Sidebar -->
        <div id="right-sidebar-outer">
            <button id="toggle-right-sidebar-btn" class="sidebar-toggle-btn right-toggle"><i data-feather="x"></i></button>
            <div id="right-sidebar" class="sidebar right-sidebar">
                <div class="sidebar-content">
                    <div class="sidebar-section">
                        <div id="favorites-container" class="favorites-sidebar">
                            <h4>Favorites</h4>
                            <div id="favorites-list" class="favorites-list">
                                <!-- Favorites will be populated by JavaScript -->
                            </div>
                        </div>
                    </div>
                    <div class="sidebar-section">
                        <div id="backlinks-container" class="backlinks-sidebar">
                            <h4>Backlinks</h4>
                            <div id="backlinks-list" class="backlinks-list">
                                <!-- Backlinks will be populated by JavaScript -->
                            </div>
                        </div>
                    </div>
                    <div class="sidebar-section">
                        <div id="child-pages-sidebar" class="child-pages-sidebar">
                            <!-- Child pages will be populated by JavaScript -->
                        </div>
                    </div>
                    <div class="sidebar-section extensions-section">
                        <h4>Extensions</h4>
                        <div id="extension-icons-container"></div>
                    </div>
                </div>
            </div>
        </div>
        
        <!-- Save Status Indicator -->
        <div id="save-status-indicator" title="All changes saved"></div>
        <button id="toggle-splash-btn" class="action-button round-button absolute-bottom-right" title="Toggle Splash Screen">
            <i data-feather="pause-circle"></i>
        </button>
    </div>

    <!-- Password Modal for Encrypted Pages -->
    <div id="password-modal" class="generic-modal">
        <div class="modal-content">
            <div class="generic-modal-header">
                <h2 class="generic-modal-title">Encrypted Page</h2>
                <button id="password-modal-close" class="modal-close-x" aria-label="Close">
                    <i data-feather="x"></i>
                </button>
            </div>
            <p>This page is encrypted. Please enter the password to view it.</p>
            <input type="password" id="password-input" placeholder="Password" class="full-width-input">
            <div class="generic-modal-actions">
                <button id="password-submit" class="button">Decrypt</button>
                <button id="password-cancel" class="button button-secondary">Cancel</button>
            </div>
        </div>
    </div>

    <!-- Encryption Password Modal -->
    <div id="encryption-password-modal" class="generic-modal">
        <div class="modal-content">
            <div class="generic-modal-header">
                <h2 class="generic-modal-title">Set Encryption Password</h2>
                <button id="encryption-modal-close" class="modal-close-x" aria-label="Close">
                    <i data-feather="x"></i>
                </button>
            </div>
            <div class="modal-body">
                <p>Enter a password to encrypt this page:</p>
                <input type="password" id="new-encryption-password" class="generic-modal-input-field" placeholder="New Password">
                <p>Confirm your password:</p>
                <input type="password" id="confirm-encryption-password" class="generic-modal-input-field" placeholder="Confirm Password">
                <p id="encryption-password-error" class="error-message" style="display: none;"></p>
            </div>
            <div class="generic-modal-actions">
                <button id="confirm-encryption-btn" class="button primary-button">Encrypt</button>
                <button id="cancel-encryption-btn" class="button secondary-button">Cancel</button>
            </div>
        </div>
    </div>

    <!-- Page Properties Modal -->
    <div id="page-properties-modal" class="generic-modal">
        <div class="modal-content">
            <div class="generic-modal-header">
                <h2 id="page-properties-modal-title" class="generic-modal-title">Page Properties</h2>
                <div class="modal-header-icons">
                    <button id="page-properties-modal-close" class="modal-close-x" aria-label="Close">
                        <i data-feather="x"></i>
                    </button>
                </div>
            </div>
            <div id="page-properties-list" class="page-properties-list"></div>
            <div class="generic-modal-actions">
                <button id="page-encryption-button" class="button" title="Encrypt Page">
                    Encrypt
                </button>
                <button id="save-page-content-btn" class="button">Save</button>
            </div>
        </div>
    </div>

    <div id="page-search-modal" class="generic-modal">
        <div class="generic-modal-content page-search-modal-styling">
            <input type="text" id="page-search-modal-input" class="generic-modal-input-field" placeholder="Type to search or create...">
            <ul id="page-search-modal-results" class="page-search-results-list"></ul>
            <div class="generic-modal-actions">
                <button id="page-search-modal-cancel" class="button secondary-button">Cancel</button>
            </div>
        </div>
    </div>
    
    <div id="image-viewer-modal" class="generic-modal image-viewer">
        <div class="generic-modal-content">
             <button id="image-viewer-modal-close" class="modal-close-x" aria-label="Close">
                <i data-feather="x"></i>
            </button>
            <img id="image-viewer-modal-img" src="" alt="Full size view">
        </div>
    </div>

    <!-- Scripts -->
    <script src="assets/libs/sjcl.js"></script>
    <script src="assets/js/splash.js"></script>
    <script type="module" src="assets/js/app.js"></script>
</body>
</html>