<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pomodoro Timer</title>
    <!-- Theme and App Styles -->
    <?php include '../../assets/css/theme_loader.php'; ?>
    <link rel="stylesheet" type="text/css" href="../../assets/css/style.css">
    <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
    <div id="pomodoro-container">
        <div class="time-date-container">
            <div id="clock" class="clock">12:00</div>
            <div id="date" class="date">Monday, 1 January</div>
        </div>
        <div id="pomodoro-background-bubbles-canvas">
            <!-- Canvas for dynamic bubbles -->
        </div>
        <div id="pomodoro-orb-container">
            <div id="pomodoro-orb-inner-core">
                <div id="timer-display">25:00</div>
                <div id="controls">
                    <button id="start">Start</button>
                    <button id="pause" style="display: none;">Pause</button>
                    <button id="reset">Reset</button>
                </div>
                <div id="pomodoro-orb-perimeter-dots">
                    <!-- Dots will be generated by JS -->
                </div>
            </div>
        </div>
    </div>
    
    <script src="animations.js"></script>
    <script src="main.js"></script>
</body>
</html>
