name: PHP CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: sqlite3, pdo_sqlite, fileinfo, curl
        tools: composer

    - name: Validate composer.json
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Start server
      run: php -S localhost:8000 -t ./ &
      
    - name: Wait for server to start
      run: |
        echo "Waiting for server to come up..."
        for i in {1..10}; do
          curl -s http://localhost:8000/index.php > /dev/null && break
          sleep 1
        done
        echo "Server is up!"

    - name: Run PHPUnit tests
      run: ./vendor/bin/phpunit --configuration phpunit.xml --process-isolation
